### ISSUE TITLE
document pixelpulse2 environment modifications for hardware debug

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/m1k-cad#5]
IO can be flipped using:

> session.devices[0].ctrl_transfer(0x50, GPIO, 0) // sets pin GPIO low
> session.devices[0].ctrl_transfer(0x51, GPIO, 0) // sets pin GPIO high

Reference https://github.com/itdaniher/ubuild/blob/master/IO.mkd for IO pinmappings. Add 32 (PORTA offset) to all PortB IO indexes.

> session.devices[0].ctrl_transfer(0x59, 0, 0x7f7f) // sets chA pot to max resistance

@mbanciso hopefully this helps.

**Comment by itdaniher** [comment]
I optimised the setpoint voltage for SIMV zero, 4/5 of 32768, at https://github.com/analogdevicesinc/libsmu/commit/bfa3314ebaac27454466e0be98eda4af91aea111. This seems to result in an experimentally minimal bias current in SIMV.

**Comment by itdaniher** [comment]
https://github.com/analogdevicesinc/m1k-fw/blob/master/IO.mkd

**Comment by itdaniher** [comment]
@damercer see additional thoughts here.

**Comment by damercer** [comment]
What am I suppose to look at?

**Comment by itdaniher** [comment]
@damercer https://github.com/analogdevicesinc/m1k-fw/blob/master/IO.mkd

**Comment by itdaniher** [comment]
https://github.com/analogdevicesinc/m1k-fw/blob/master/IO.mkd now describes the control transfers usable to directly manipulate device state.
